{{- include "ffc-helm-library.container-config-map" (list . "bng-credits-estimator.config-map") -}}
{{- define "bng-credits-estimator.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
{{- end -}}
