environment: production
environmentCode:
name: bng-credits-estimator
namespace: bng-credits
workstream: bng-credits
image: bng-credits-estimator

labels:
  component: service

containerConfigMap:
  name: bng-credits-estimator-config-map

containerSecret:
  name: bng-credits-estimator-container-secret
  type: Opaque

deployment:
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 0
  minReplicas: 1
  maxReplicas: 2
  priorityClassName: high
  replicas: 1
  restartPolicy: Always

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000

ingress:
  class: nginx
  endpoint: bng-credits-estimator
  server: example.com

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
